import { ReactNode } from 'react'
import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'

import '../styles/globals.css'

const roboto = Roboto({ weight: ['400', '700', '900'], subsets: ['latin'] })

interface RootLayoutProps {
    children: ReactNode
}

export const metadata: Metadata = {
    title: 'NLW copas game calendar',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            <body
                className={`${roboto.className} bg-gray-900 bg-app bg-no-repeat bg-cover bg-center`}
            >
                {children}
            </body>
        </html>
    )
}
